version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/buzzify
    environment:
      - ENV=production

  frontend:
    build: ./Frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
