name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flask flask-socketio flask-cors eventlet pylint

    - name: Analysing the code with pylint
      run: |
        pylint --disable=unused-import $(git ls-files '*.py')

    - name: Check Pylint Score
      run: |
        SCORE=$(pylint $(git ls-files '*.py') | tee pylint-report.txt | grep -o "rated at [0-9.]\+" | awk '{print $3}')
        echo "Pylint score: $SCORE"
        if (( $(echo "$SCORE < 8" | bc -l) )); then
          echo "Pylint score ($SCORE) is below 8. Build failed."
          exit 1
        fi
